// This file was generated by the Pelion SDK foundation code generator.
// This is an autogenerated unit test class. Do not modify its content as modifications will be lost at next code generation.
package com.arm.mbed.cloud.sdk.security.model;

import static org.junit.Assert.*;

import org.junit.Test;

/**
 * Unit tests for Model CertificateEnrollmentListDao.
 */
@SuppressWarnings("PMD.AvoidDuplicateLiterals")
public class TestCertificateEnrollmentListDao {
    /**
     * Tests the clone method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testClone() {
        try {
            CertificateEnrollmentListDao certificateenrollmentlistdao1 = new CertificateEnrollmentListDao();
            CertificateEnrollmentListDao certificateenrollmentlistdao2 = certificateenrollmentlistdao1.clone();
            assertNotNull(certificateenrollmentlistdao1);
            assertNotNull(certificateenrollmentlistdao2);
            assertNotSame(certificateenrollmentlistdao2, certificateenrollmentlistdao1);
            assertEquals(certificateenrollmentlistdao2, certificateenrollmentlistdao1);
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }

    /**
     * Tests the hashCode method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testHashCode() {
        try {
            CertificateEnrollmentListDao certificateenrollmentlistdao1 = new CertificateEnrollmentListDao();
            CertificateEnrollmentListDao certificateenrollmentlistdao2 = new CertificateEnrollmentListDao();
            assertNotNull(certificateenrollmentlistdao1);
            assertNotNull(certificateenrollmentlistdao2);
            assertNotSame(certificateenrollmentlistdao2, certificateenrollmentlistdao1);
            assertEquals(certificateenrollmentlistdao2, certificateenrollmentlistdao1);
            assertEquals(certificateenrollmentlistdao2.hashCode(), certificateenrollmentlistdao1.hashCode());
            int hashCode = certificateenrollmentlistdao1.hashCode();
            for (int i = 0; i < 5; i++) {
                assertEquals(hashCode, certificateenrollmentlistdao1.hashCode());
            }
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }

    /**
     * Tests the equals method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testEquals() {
        try {
            CertificateEnrollmentListDao certificateenrollmentlistdao1 = new CertificateEnrollmentListDao();
            CertificateEnrollmentListDao certificateenrollmentlistdao2 = new CertificateEnrollmentListDao();
            assertNotNull(certificateenrollmentlistdao1);
            assertNotNull(certificateenrollmentlistdao2);
            assertNotSame(certificateenrollmentlistdao2, certificateenrollmentlistdao1);
            assertEquals(certificateenrollmentlistdao2, certificateenrollmentlistdao1);
            assertEquals(certificateenrollmentlistdao2, certificateenrollmentlistdao1);
            assertEquals(certificateenrollmentlistdao1, certificateenrollmentlistdao2);
            assertEquals(certificateenrollmentlistdao1, certificateenrollmentlistdao1);
            assertFalse(certificateenrollmentlistdao1.equals(null));
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }
}
