// This file was generated by the Pelion SDK foundation code generator.
// This is an autogenerated unit test class. Do not modify its content as modifications will be lost at next code generation.
package com.arm.mbed.cloud.sdk.branding.model;

import static org.junit.Assert.*;

import java.util.Date;
import org.junit.Test;

/**
 * Unit tests for Model LightThemeImage.
 */
@SuppressWarnings("PMD.AvoidDuplicateLiterals")
public class TestLightThemeImage {
    /**
     * Tests the clone method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testClone() {
        try {
            LightThemeImage lightthemeimage1 = new LightThemeImage(LightThemeImageReference.getDefault(),
                                                                   "80e08fd1-c3eb-4920-bf7b-d55c89c3440c",
                                                                   new Date(1559752148053L));
            LightThemeImage lightthemeimage2 = lightthemeimage1.clone();
            assertNotNull(lightthemeimage1);
            assertNotNull(lightthemeimage2);
            assertNotSame(lightthemeimage2, lightthemeimage1);
            assertEquals(lightthemeimage2, lightthemeimage1);
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }

    /**
     * Tests the hashCode method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testHashCode() {
        try {
            LightThemeImage lightthemeimage1 = new LightThemeImage(LightThemeImageReference.getDefault(),
                                                                   "54560c5d-2ae2-4ea6-af20-e7bc246489d5",
                                                                   new Date(1559752152835L));
            LightThemeImage lightthemeimage2 = new LightThemeImage(LightThemeImageReference.getDefault(),
                                                                   "54560c5d-2ae2-4ea6-af20-e7bc246489d5",
                                                                   new Date(1559752152835L));
            assertNotNull(lightthemeimage1);
            assertNotNull(lightthemeimage2);
            assertNotSame(lightthemeimage2, lightthemeimage1);
            assertEquals(lightthemeimage2, lightthemeimage1);
            assertEquals(lightthemeimage2.hashCode(), lightthemeimage1.hashCode());
            int hashCode = lightthemeimage1.hashCode();
            for (int i = 0; i < 5; i++) {
                assertEquals(hashCode, lightthemeimage1.hashCode());
            }
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }

    /**
     * Tests the isValid method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testIsValid() {
        LightThemeImage lightthemeimage = new LightThemeImage(LightThemeImageReference.getDefault(),
                                                              "419aa5d6-630e-4e1a-b147-6b35358c3d1f",
                                                              new Date(1559752153484L));
        assertTrue(lightthemeimage.isValid());
        LightThemeImage lightthemeimageInvalid = new LightThemeImage(LightThemeImageReference.getDefault(),
                                                                     "b954196c-d123-4840-a1bf-0e2717dc97b4",
                                                                     new Date(1559752149052L));
        assertFalse(lightthemeimageInvalid.isValid());
    }

    /**
     * Tests the equals method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testEquals() {
        try {
            LightThemeImage lightthemeimage1 = new LightThemeImage(LightThemeImageReference.getDefault(),
                                                                   "24cab900-eef7-43dc-9075-8a924dd48647",
                                                                   new Date(1559752144695L));
            LightThemeImage lightthemeimage2 = new LightThemeImage(LightThemeImageReference.getDefault(),
                                                                   "24cab900-eef7-43dc-9075-8a924dd48647",
                                                                   new Date(1559752144695L));
            LightThemeImage lightthemeimage3 = new LightThemeImage(LightThemeImageReference.getDefault(),
                                                                   "9a33ce15-2e31-4024-88a8-a601713506a5",
                                                                   new Date(1559752146283L));
            assertNotNull(lightthemeimage1);
            assertNotNull(lightthemeimage2);
            assertNotNull(lightthemeimage3);
            assertNotSame(lightthemeimage2, lightthemeimage1);
            assertNotSame(lightthemeimage3, lightthemeimage1);
            assertEquals(lightthemeimage2, lightthemeimage1);
            assertEquals(lightthemeimage2, lightthemeimage1);
            assertEquals(lightthemeimage1, lightthemeimage2);
            assertEquals(lightthemeimage1, lightthemeimage1);
            assertFalse(lightthemeimage1.equals(null));
            assertNotEquals(lightthemeimage3, lightthemeimage1);
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }
}
