// This file was generated by the Pelion SDK foundation code generator.
// This model class was autogenerated on Tue Jun 04 15:39:38 UTC 2019. Feel free to change its contents as you wish.
package com.arm.mbed.cloud.sdk.branding.model;

import com.arm.mbed.cloud.sdk.annotations.NotImplemented;
import com.arm.mbed.cloud.sdk.annotations.Preamble;
import com.arm.mbed.cloud.sdk.common.ApiClientWrapper;
import com.arm.mbed.cloud.sdk.common.ConnectionOptions;
import com.arm.mbed.cloud.sdk.common.MbedCloudException;
import com.arm.mbed.cloud.sdk.common.NotImplementedException;
import com.arm.mbed.cloud.sdk.common.SdkContext;
import com.arm.mbed.cloud.sdk.common.listing.ListResponse;

/**
 * Data Access Object (DAO) for listing subtenant dark theme colors.
 * <p>
 * 
 * @see <a href="http://www.corej2eepatterns.com/Patterns/DataAccessObject.htm">Core J2EE Patterns - Data Access
 *      Object</a>
 */
@Preamble(description = "Data Access Object (DAO) for listing subtenant dark theme colors.")
public class SubtenantDarkThemeColorListDao extends AbstractSubtenantDarkThemeColorListDao {
    /**
     * Constructor.
     * 
     * @throws MbedCloudException
     *             if an error occurs during the process.
     */
    public SubtenantDarkThemeColorListDao() throws MbedCloudException {
        super();
    }

    /**
     * Constructor.
     * 
     * @param client
     *            an api client wrapper.
     * @throws MbedCloudException
     *             if an error occurs during the process.
     */
    public SubtenantDarkThemeColorListDao(ApiClientWrapper client) throws MbedCloudException {
        super(client);
    }

    /**
     * Constructor.
     * 
     * @param options
     *            a connection options.
     * @throws MbedCloudException
     *             if an error occurs during the process.
     */
    public SubtenantDarkThemeColorListDao(ConnectionOptions options) throws MbedCloudException {
        super(options);
    }

    /**
     * Constructor.
     * 
     * @param sdkContext
     *            an sdk context.
     * @throws MbedCloudException
     *             if an error occurs during the process.
     */
    public SubtenantDarkThemeColorListDao(SdkContext sdkContext) throws MbedCloudException {
        super(sdkContext);
    }

    /**
     * Clones this instance.
     *
     * <p>
     * 
     * @see java.lang.Object#clone()
     * @return a cloned instance
     */
    @Override
    @SuppressWarnings({ "resource", "unused" })
    public SubtenantDarkThemeColorListDao clone() {
        try {
            return new SubtenantDarkThemeColorListDao().configureAndGet(getModuleOrThrow() == null ? null
                                                                                                   : getModuleOrThrow().clone());
        } catch (MbedCloudException exception) {
            return null;
        }
    }

    /**
     * Lists subtenant dark theme colors matching filter options.
     *
     * <p>
     * Similar to
     * {@link com.arm.mbed.cloud.sdk.Branding#listSubtenantDarkThemeColors(String, com.arm.mbed.cloud.sdk.branding.model.SubtenantDarkThemeColorListOptions)}
     * 
     * @param options
     *            list options.
     * @return one page of subtenant dark theme colors
     * @throws MbedCloudException
     *             if an error occurs during the process.
     */
    @Override
    @NotImplemented
    protected ListResponse<SubtenantDarkThemeColor>
              requestOnePage(SubtenantDarkThemeColorListOptions options) throws MbedCloudException,
                                                                         NotImplementedException {
        // TODO Auto-generated method stub.;
        throw new NotImplementedException();
        // The following code is auto-generated and can be used if carrying out what requestOnePage() intends/is meant
        // to do.

        /*
         * return ((Branding)getModuleOrThrow()).listSubtenantDarkThemeColors((String) null, options);
         */
    }
}
