// This file was generated by the Pelion SDK foundation code generator.
// This is an autogenerated abstract class. Do not modify its contents.
// Code customisation should happen in the child class [AccountListDao]
package com.arm.mbed.cloud.sdk.accounts.model;

import com.arm.mbed.cloud.sdk.Accounts;
import com.arm.mbed.cloud.sdk.annotations.Internal;
import com.arm.mbed.cloud.sdk.annotations.Preamble;
import com.arm.mbed.cloud.sdk.common.ApiClientWrapper;
import com.arm.mbed.cloud.sdk.common.ConnectionOptions;
import com.arm.mbed.cloud.sdk.common.MbedCloudException;
import com.arm.mbed.cloud.sdk.common.SdkContext;
import com.arm.mbed.cloud.sdk.common.dao.AbstractModelListDao;
import com.arm.mbed.cloud.sdk.common.dao.ModelListDao;
import java.lang.Class;
import java.lang.CloneNotSupportedException;
import java.lang.Object;
import java.lang.Override;

/**
 * Data Access Object (DAO) for listing accounts.
 * <p>
 * @see <a  href="http://www.corej2eepatterns.com/Patterns/DataAccessObject.htm">Core J2EE Patterns - Data Access Object</a> */
@Preamble(
    description = "Data Access Object (DAO) for listing accounts."
)
public abstract class AbstractAccountListDao extends AbstractModelListDao<Account, AccountListOptions> implements ModelListDao<Account> {
  /**
   * Constructor.
   */
  public AbstractAccountListDao() throws MbedCloudException {
    super();
  }

  /**
   * Instantiates modules.
   * @param client an api client wrapper.
   * @return instantiated module
   */
  @Override
  @Internal
  protected SdkContext instantiateModule(ApiClientWrapper client) {
    return new Accounts(client);
  }

  /**
   * Instantiates modules.
   * @param context an sdk context.
   * @return instantiated module
   */
  @Override
  @Internal
  protected SdkContext instantiateModule(SdkContext context) {
    return new Accounts(context);
  }

  /**
   * Instantiates modules.
   * @param options a connection options.
   * @return instantiated module
   */
  @Override
  @Internal
  protected SdkContext instantiateModule(ConnectionOptions options) {
    return new Accounts(options);
  }

  /**
   * an account list options.
   * @return an account list options
   */
  @Override
  @Internal
  protected AccountListOptions instantiateListOptions() {
    return new AccountListOptions();
  }

  /**
   * an account dao class.
   * @return an account dao class
   */
  @Override
  @Internal
  public Class<AccountDao> getCorrespondingModelDaoDefinition() {
    return AccountDao.class;
  }

  /**
   * an account dao.
   * @return an account dao
   */
  @Override
  @Internal
  public AccountDao getCorrespondingModelDao() {
    return new AccountDao().configureAndGet(module);
  }

  /**
   * Clones this instance.
   * <p>
   * @see java.lang.Object#clone()
   * @return a cloned instance
   */
  @Override
  public Object clone() {
    try {
      return super.clone();
    }
    catch(CloneNotSupportedException exception) {
      return null;
    }
  }
}
