// This file was generated by the Pelion SDK foundation code generator.
// This is an autogenerated unit test class. Do not modify its content as modifications will be lost at next code generation.
package com.arm.mbed.cloud.sdk.deviceupdate.model;

import static org.junit.Assert.*;

import com.arm.mbed.cloud.sdk.common.Order;
import org.junit.Test;

/**
 * Unit tests for Model CampaignStatisticsListOptions.
 */
@SuppressWarnings("PMD.AvoidDuplicateLiterals")
public class TestCampaignStatisticsListOptions {
    /**
     * Tests the clone method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testClone() {
        try {
            CampaignStatisticsListOptions campaignstatisticslistoptions1 = new CampaignStatisticsListOptions(Integer.valueOf(113),
                                                                                                             Long.valueOf(-64),
                                                                                                             Order.getDefault(),
                                                                                                             "9f593e04-070b-42ee-8f96-7f8b4b51b7c5",
                                                                                                             null,
                                                                                                             null);
            CampaignStatisticsListOptions campaignstatisticslistoptions2 = campaignstatisticslistoptions1.clone();
            assertNotNull(campaignstatisticslistoptions1);
            assertNotNull(campaignstatisticslistoptions2);
            assertNotSame(campaignstatisticslistoptions2, campaignstatisticslistoptions1);
            assertEquals(campaignstatisticslistoptions2, campaignstatisticslistoptions1);
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }

    /**
     * Tests the hashCode method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testHashCode() {
        try {
            CampaignStatisticsListOptions campaignstatisticslistoptions1 = new CampaignStatisticsListOptions(Integer.valueOf(114),
                                                                                                             Long.valueOf(-91),
                                                                                                             Order.getDefault(),
                                                                                                             "755ed6fe-1908-41ec-b0e0-501e05d842e8",
                                                                                                             null,
                                                                                                             null);
            CampaignStatisticsListOptions campaignstatisticslistoptions2 = new CampaignStatisticsListOptions(Integer.valueOf(114),
                                                                                                             Long.valueOf(-91),
                                                                                                             Order.getDefault(),
                                                                                                             "755ed6fe-1908-41ec-b0e0-501e05d842e8",
                                                                                                             null,
                                                                                                             null);
            assertNotNull(campaignstatisticslistoptions1);
            assertNotNull(campaignstatisticslistoptions2);
            assertNotSame(campaignstatisticslistoptions2, campaignstatisticslistoptions1);
            assertEquals(campaignstatisticslistoptions2, campaignstatisticslistoptions1);
            assertEquals(campaignstatisticslistoptions2.hashCode(), campaignstatisticslistoptions1.hashCode());
            int hashCode = campaignstatisticslistoptions1.hashCode();
            for (int i = 0; i < 5; i++) {
                assertEquals(hashCode, campaignstatisticslistoptions1.hashCode());
            }
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }

    /**
     * Tests the equals method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testEquals() {
        try {
            CampaignStatisticsListOptions campaignstatisticslistoptions1 = new CampaignStatisticsListOptions(Integer.valueOf(67),
                                                                                                             Long.valueOf(79),
                                                                                                             Order.getDefault(),
                                                                                                             "874cfae6-ac9c-45b4-aa88-5cb5cdb34dfe",
                                                                                                             null,
                                                                                                             null);
            CampaignStatisticsListOptions campaignstatisticslistoptions2 = new CampaignStatisticsListOptions(Integer.valueOf(67),
                                                                                                             Long.valueOf(79),
                                                                                                             Order.getDefault(),
                                                                                                             "874cfae6-ac9c-45b4-aa88-5cb5cdb34dfe",
                                                                                                             null,
                                                                                                             null);
            CampaignStatisticsListOptions campaignstatisticslistoptions3 = new CampaignStatisticsListOptions(Integer.valueOf(40),
                                                                                                             Long.valueOf(-58),
                                                                                                             Order.getDefault(),
                                                                                                             "651b872b-9bee-478b-8ec1-1ca45d91cc65",
                                                                                                             null,
                                                                                                             null);
            assertNotNull(campaignstatisticslistoptions1);
            assertNotNull(campaignstatisticslistoptions2);
            assertNotNull(campaignstatisticslistoptions3);
            assertNotSame(campaignstatisticslistoptions2, campaignstatisticslistoptions1);
            assertNotSame(campaignstatisticslistoptions3, campaignstatisticslistoptions1);
            assertEquals(campaignstatisticslistoptions2, campaignstatisticslistoptions1);
            assertEquals(campaignstatisticslistoptions2, campaignstatisticslistoptions1);
            assertEquals(campaignstatisticslistoptions1, campaignstatisticslistoptions2);
            assertEquals(campaignstatisticslistoptions1, campaignstatisticslistoptions1);
            assertFalse(campaignstatisticslistoptions1.equals(null));
            assertNotEquals(campaignstatisticslistoptions3, campaignstatisticslistoptions1);
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }
}
