/*
 * Pelion Device Management API
 * Pelion Device Management API build from the publicly defined API definitions.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.arm.mbed.cloud.sdk.lowlevel.pelionclouddevicemanagement.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * Used as default value if parent entity has this limitation defined. If parent entity does not have such a limitation,
 * the value is null.
 */
@ApiModel(description = "Used as default value if parent entity has this limitation defined. If parent entity does not have such a limitation, the value is null.")

public class AccountLimitationInheritedValue implements Serializable {
    private static final long serialVersionUID = 1L;

    @SerializedName("billing_period")
    private Integer billingPeriod = null;

    @SerializedName("limit")
    private Long limit = null;

    @SerializedName("quota")
    private Long quota = null;

    public AccountLimitationInheritedValue billingPeriod(Integer billingPeriod) {
        this.billingPeriod = billingPeriod;
        return this;
    }

    /**
     * Default billing period of the account limitation as defined in the parent entity. minimum: 1 maximum: 120
     * 
     * @return billingPeriod
     **/
    @ApiModelProperty(example = "1",
                      value = "Default billing period of the account limitation as defined in the parent entity.")
    public Integer getBillingPeriod() {
        return billingPeriod;
    }

    public void setBillingPeriod(Integer billingPeriod) {
        this.billingPeriod = billingPeriod;
    }

    public AccountLimitationInheritedValue limit(Long limit) {
        this.limit = limit;
        return this;
    }

    /**
     * Default value of the limit as defined in the parent entity.
     * 
     * @return limit
     **/
    @ApiModelProperty(example = "25", value = "Default value of the limit as defined in the parent entity.")
    public Long getLimit() {
        return limit;
    }

    public void setLimit(Long limit) {
        this.limit = limit;
    }

    public AccountLimitationInheritedValue quota(Long quota) {
        this.quota = quota;
        return this;
    }

    /**
     * Default quota as defined in the parent entity.
     * 
     * @return quota
     **/
    @ApiModelProperty(example = "0", value = "Default quota as defined in the parent entity.")
    public Long getQuota() {
        return quota;
    }

    public void setQuota(Long quota) {
        this.quota = quota;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AccountLimitationInheritedValue accountLimitationInheritedValue = (AccountLimitationInheritedValue) o;
        return Objects.equals(this.billingPeriod, accountLimitationInheritedValue.billingPeriod)
               && Objects.equals(this.limit, accountLimitationInheritedValue.limit)
               && Objects.equals(this.quota, accountLimitationInheritedValue.quota);
    }

    @Override
    public int hashCode() {
        return Objects.hash(billingPeriod, limit, quota);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AccountLimitationInheritedValue {\n");

        sb.append("    billingPeriod: ").append(toIndentedString(billingPeriod)).append("\n");
        sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
        sb.append("    quota: ").append(toIndentedString(quota)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
