/*
 * Update Service API
 * This is the API Documentation for the mbed deployment service which is part of the update service.
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.arm.mbed.cloud.sdk.internal.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * ManifestContentsPayloadInfoFormat
 */

public class ManifestContentsPayloadInfoFormat implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("enum")
  private String _enum = null;

  @SerializedName("objectId")
  private String objectId = null;

  public ManifestContentsPayloadInfoFormat _enum(String _enum) {
    this._enum = _enum;
    return this;
  }

   /**
   * Get _enum
   * @return _enum
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEnum() {
    return _enum;
  }

  public void setEnum(String _enum) {
    this._enum = _enum;
  }

  public ManifestContentsPayloadInfoFormat objectId(String objectId) {
    this.objectId = objectId;
    return this;
  }

   /**
   * Get objectId
   * @return objectId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getObjectId() {
    return objectId;
  }

  public void setObjectId(String objectId) {
    this.objectId = objectId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManifestContentsPayloadInfoFormat manifestContentsPayloadInfoFormat = (ManifestContentsPayloadInfoFormat) o;
    return Objects.equals(this._enum, manifestContentsPayloadInfoFormat._enum) &&
        Objects.equals(this.objectId, manifestContentsPayloadInfoFormat.objectId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_enum, objectId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManifestContentsPayloadInfoFormat {\n");
    
    sb.append("    _enum: ").append(toIndentedString(_enum)).append("\n");
    sb.append("    objectId: ").append(toIndentedString(objectId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

