// This file was generated by the Pelion SDK foundation code generator.
// This is an autogenerated unit test class. Do not modify its content as modifications will be lost at next code generation.
package com.arm.mbed.cloud.sdk.branding.model;

import static org.junit.Assert.*;

import com.arm.mbed.cloud.sdk.common.Order;
import org.junit.Test;

/**
 * Unit tests for Model LightThemeImageListOptions.
 */
@SuppressWarnings("PMD.AvoidDuplicateLiterals")
public class TestLightThemeImageListOptions {
    /**
     * Tests the clone method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testClone() {
        try {
            LightThemeImageListOptions lightthemeimagelistoptions1 = new LightThemeImageListOptions(Integer.valueOf(104),
                                                                                                    Long.valueOf(-30),
                                                                                                    Order.getDefault(),
                                                                                                    "9ac0ede6-c758-4328-9142-a644db015cdb",
                                                                                                    null, null);
            LightThemeImageListOptions lightthemeimagelistoptions2 = lightthemeimagelistoptions1.clone();
            assertNotNull(lightthemeimagelistoptions1);
            assertNotNull(lightthemeimagelistoptions2);
            assertNotSame(lightthemeimagelistoptions2, lightthemeimagelistoptions1);
            assertEquals(lightthemeimagelistoptions2, lightthemeimagelistoptions1);
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }

    /**
     * Tests the hashCode method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testHashCode() {
        try {
            LightThemeImageListOptions lightthemeimagelistoptions1 = new LightThemeImageListOptions(Integer.valueOf(73),
                                                                                                    Long.valueOf(-18),
                                                                                                    Order.getDefault(),
                                                                                                    "6bfe7b20-3bf3-44ac-b57f-fb7c96cfe78f",
                                                                                                    null, null);
            LightThemeImageListOptions lightthemeimagelistoptions2 = new LightThemeImageListOptions(Integer.valueOf(73),
                                                                                                    Long.valueOf(-18),
                                                                                                    Order.getDefault(),
                                                                                                    "6bfe7b20-3bf3-44ac-b57f-fb7c96cfe78f",
                                                                                                    null, null);
            assertNotNull(lightthemeimagelistoptions1);
            assertNotNull(lightthemeimagelistoptions2);
            assertNotSame(lightthemeimagelistoptions2, lightthemeimagelistoptions1);
            assertEquals(lightthemeimagelistoptions2, lightthemeimagelistoptions1);
            assertEquals(lightthemeimagelistoptions2.hashCode(), lightthemeimagelistoptions1.hashCode());
            int hashCode = lightthemeimagelistoptions1.hashCode();
            for (int i = 0; i < 5; i++) {
                assertEquals(hashCode, lightthemeimagelistoptions1.hashCode());
            }
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }

    /**
     * Tests the equals method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testEquals() {
        try {
            LightThemeImageListOptions lightthemeimagelistoptions1 = new LightThemeImageListOptions(Integer.valueOf(61),
                                                                                                    Long.valueOf(-121),
                                                                                                    Order.getDefault(),
                                                                                                    "fc20ee24-3241-48cf-b521-b84a258a17dc",
                                                                                                    null, null);
            LightThemeImageListOptions lightthemeimagelistoptions2 = new LightThemeImageListOptions(Integer.valueOf(61),
                                                                                                    Long.valueOf(-121),
                                                                                                    Order.getDefault(),
                                                                                                    "fc20ee24-3241-48cf-b521-b84a258a17dc",
                                                                                                    null, null);
            LightThemeImageListOptions lightthemeimagelistoptions3 = new LightThemeImageListOptions(Integer.valueOf(80),
                                                                                                    Long.valueOf(92),
                                                                                                    Order.getDefault(),
                                                                                                    "a206abd7-8c6c-4b85-befe-54e155180b1c",
                                                                                                    null, null);
            assertNotNull(lightthemeimagelistoptions1);
            assertNotNull(lightthemeimagelistoptions2);
            assertNotNull(lightthemeimagelistoptions3);
            assertNotSame(lightthemeimagelistoptions2, lightthemeimagelistoptions1);
            assertNotSame(lightthemeimagelistoptions3, lightthemeimagelistoptions1);
            assertEquals(lightthemeimagelistoptions2, lightthemeimagelistoptions1);
            assertEquals(lightthemeimagelistoptions2, lightthemeimagelistoptions1);
            assertEquals(lightthemeimagelistoptions1, lightthemeimagelistoptions2);
            assertEquals(lightthemeimagelistoptions1, lightthemeimagelistoptions1);
            assertFalse(lightthemeimagelistoptions1.equals(null));
            assertNotEquals(lightthemeimagelistoptions3, lightthemeimagelistoptions1);
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }
}
