// This file was generated by the Pelion SDK foundation code generator.
// This is an autogenerated unit test class. Do not modify its content as modifications will be lost at next code generation.
package com.arm.mbed.cloud.sdk.branding.model;

import static org.junit.Assert.*;

import com.arm.mbed.cloud.sdk.common.Order;
import org.junit.Test;

/**
 * Unit tests for Model SubtenantDarkThemeImageListOptions.
 */
@SuppressWarnings("PMD.AvoidDuplicateLiterals")
public class TestSubtenantDarkThemeImageListOptions {
    /**
     * Tests the clone method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testClone() {
        try {
            SubtenantDarkThemeImageListOptions subtenantdarkthemeimagelistoptions1 = new SubtenantDarkThemeImageListOptions(Integer.valueOf(-58),
                                                                                                                            Long.valueOf(-14),
                                                                                                                            Order.getDefault(),
                                                                                                                            "6590708d-afdd-4612-a3df-ae5cdaabf23d",
                                                                                                                            null,
                                                                                                                            null);
            SubtenantDarkThemeImageListOptions subtenantdarkthemeimagelistoptions2 = subtenantdarkthemeimagelistoptions1.clone();
            assertNotNull(subtenantdarkthemeimagelistoptions1);
            assertNotNull(subtenantdarkthemeimagelistoptions2);
            assertNotSame(subtenantdarkthemeimagelistoptions2, subtenantdarkthemeimagelistoptions1);
            assertEquals(subtenantdarkthemeimagelistoptions2, subtenantdarkthemeimagelistoptions1);
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }

    /**
     * Tests the hashCode method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testHashCode() {
        try {
            SubtenantDarkThemeImageListOptions subtenantdarkthemeimagelistoptions1 = new SubtenantDarkThemeImageListOptions(Integer.valueOf(-105),
                                                                                                                            Long.valueOf(-13),
                                                                                                                            Order.getDefault(),
                                                                                                                            "e6a53602-a99e-4677-9ab5-93bf5691c00b",
                                                                                                                            null,
                                                                                                                            null);
            SubtenantDarkThemeImageListOptions subtenantdarkthemeimagelistoptions2 = new SubtenantDarkThemeImageListOptions(Integer.valueOf(-105),
                                                                                                                            Long.valueOf(-13),
                                                                                                                            Order.getDefault(),
                                                                                                                            "e6a53602-a99e-4677-9ab5-93bf5691c00b",
                                                                                                                            null,
                                                                                                                            null);
            assertNotNull(subtenantdarkthemeimagelistoptions1);
            assertNotNull(subtenantdarkthemeimagelistoptions2);
            assertNotSame(subtenantdarkthemeimagelistoptions2, subtenantdarkthemeimagelistoptions1);
            assertEquals(subtenantdarkthemeimagelistoptions2, subtenantdarkthemeimagelistoptions1);
            assertEquals(subtenantdarkthemeimagelistoptions2.hashCode(),
                         subtenantdarkthemeimagelistoptions1.hashCode());
            int hashCode = subtenantdarkthemeimagelistoptions1.hashCode();
            for (int i = 0; i < 5; i++) {
                assertEquals(hashCode, subtenantdarkthemeimagelistoptions1.hashCode());
            }
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }

    /**
     * Tests the equals method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testEquals() {
        try {
            SubtenantDarkThemeImageListOptions subtenantdarkthemeimagelistoptions1 = new SubtenantDarkThemeImageListOptions(Integer.valueOf(96),
                                                                                                                            Long.valueOf(28),
                                                                                                                            Order.getDefault(),
                                                                                                                            "792f9eef-1ecb-4dd5-832f-7952bb20460f",
                                                                                                                            null,
                                                                                                                            null);
            SubtenantDarkThemeImageListOptions subtenantdarkthemeimagelistoptions2 = new SubtenantDarkThemeImageListOptions(Integer.valueOf(96),
                                                                                                                            Long.valueOf(28),
                                                                                                                            Order.getDefault(),
                                                                                                                            "792f9eef-1ecb-4dd5-832f-7952bb20460f",
                                                                                                                            null,
                                                                                                                            null);
            SubtenantDarkThemeImageListOptions subtenantdarkthemeimagelistoptions3 = new SubtenantDarkThemeImageListOptions(Integer.valueOf(-7),
                                                                                                                            Long.valueOf(3),
                                                                                                                            Order.getDefault(),
                                                                                                                            "ce48b073-44a8-43a7-a6cc-482e1bbb67cc",
                                                                                                                            null,
                                                                                                                            null);
            assertNotNull(subtenantdarkthemeimagelistoptions1);
            assertNotNull(subtenantdarkthemeimagelistoptions2);
            assertNotNull(subtenantdarkthemeimagelistoptions3);
            assertNotSame(subtenantdarkthemeimagelistoptions2, subtenantdarkthemeimagelistoptions1);
            assertNotSame(subtenantdarkthemeimagelistoptions3, subtenantdarkthemeimagelistoptions1);
            assertEquals(subtenantdarkthemeimagelistoptions2, subtenantdarkthemeimagelistoptions1);
            assertEquals(subtenantdarkthemeimagelistoptions2, subtenantdarkthemeimagelistoptions1);
            assertEquals(subtenantdarkthemeimagelistoptions1, subtenantdarkthemeimagelistoptions2);
            assertEquals(subtenantdarkthemeimagelistoptions1, subtenantdarkthemeimagelistoptions1);
            assertFalse(subtenantdarkthemeimagelistoptions1.equals(null));
            assertNotEquals(subtenantdarkthemeimagelistoptions3, subtenantdarkthemeimagelistoptions1);
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }
}
