// This file was generated by the Pelion SDK foundation code generator.
// This is an autogenerated unit test class. Do not modify its content as modifications will be lost at next code generation.
package com.arm.mbed.cloud.sdk.branding.model;

import static org.junit.Assert.*;

import com.arm.mbed.cloud.sdk.common.Order;
import org.junit.Test;

/**
 * Unit tests for Model DarkThemeImageListOptions.
 */
@SuppressWarnings("PMD.AvoidDuplicateLiterals")
public class TestDarkThemeImageListOptions {
    /**
     * Tests the clone method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testClone() {
        try {
            DarkThemeImageListOptions darkthemeimagelistoptions1 = new DarkThemeImageListOptions(Integer.valueOf(-32),
                                                                                                 Long.valueOf(-107),
                                                                                                 Order.getDefault(),
                                                                                                 "20f5f921-3ad9-4ce5-8670-88de15772637",
                                                                                                 null, null);
            DarkThemeImageListOptions darkthemeimagelistoptions2 = darkthemeimagelistoptions1.clone();
            assertNotNull(darkthemeimagelistoptions1);
            assertNotNull(darkthemeimagelistoptions2);
            assertNotSame(darkthemeimagelistoptions2, darkthemeimagelistoptions1);
            assertEquals(darkthemeimagelistoptions2, darkthemeimagelistoptions1);
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }

    /**
     * Tests the hashCode method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testHashCode() {
        try {
            DarkThemeImageListOptions darkthemeimagelistoptions1 = new DarkThemeImageListOptions(Integer.valueOf(-92),
                                                                                                 Long.valueOf(-123),
                                                                                                 Order.getDefault(),
                                                                                                 "908eb1c5-d985-42e4-904f-543b27253f9d",
                                                                                                 null, null);
            DarkThemeImageListOptions darkthemeimagelistoptions2 = new DarkThemeImageListOptions(Integer.valueOf(-92),
                                                                                                 Long.valueOf(-123),
                                                                                                 Order.getDefault(),
                                                                                                 "908eb1c5-d985-42e4-904f-543b27253f9d",
                                                                                                 null, null);
            assertNotNull(darkthemeimagelistoptions1);
            assertNotNull(darkthemeimagelistoptions2);
            assertNotSame(darkthemeimagelistoptions2, darkthemeimagelistoptions1);
            assertEquals(darkthemeimagelistoptions2, darkthemeimagelistoptions1);
            assertEquals(darkthemeimagelistoptions2.hashCode(), darkthemeimagelistoptions1.hashCode());
            int hashCode = darkthemeimagelistoptions1.hashCode();
            for (int i = 0; i < 5; i++) {
                assertEquals(hashCode, darkthemeimagelistoptions1.hashCode());
            }
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }

    /**
     * Tests the equals method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testEquals() {
        try {
            DarkThemeImageListOptions darkthemeimagelistoptions1 = new DarkThemeImageListOptions(Integer.valueOf(0),
                                                                                                 Long.valueOf(-81),
                                                                                                 Order.getDefault(),
                                                                                                 "d1e691c1-eb37-452b-82c6-ef74219b006e",
                                                                                                 null, null);
            DarkThemeImageListOptions darkthemeimagelistoptions2 = new DarkThemeImageListOptions(Integer.valueOf(0),
                                                                                                 Long.valueOf(-81),
                                                                                                 Order.getDefault(),
                                                                                                 "d1e691c1-eb37-452b-82c6-ef74219b006e",
                                                                                                 null, null);
            DarkThemeImageListOptions darkthemeimagelistoptions3 = new DarkThemeImageListOptions(Integer.valueOf(-107),
                                                                                                 Long.valueOf(-67),
                                                                                                 Order.getDefault(),
                                                                                                 "33c4def3-b3c8-4402-a683-e6730d79897a",
                                                                                                 null, null);
            assertNotNull(darkthemeimagelistoptions1);
            assertNotNull(darkthemeimagelistoptions2);
            assertNotNull(darkthemeimagelistoptions3);
            assertNotSame(darkthemeimagelistoptions2, darkthemeimagelistoptions1);
            assertNotSame(darkthemeimagelistoptions3, darkthemeimagelistoptions1);
            assertEquals(darkthemeimagelistoptions2, darkthemeimagelistoptions1);
            assertEquals(darkthemeimagelistoptions2, darkthemeimagelistoptions1);
            assertEquals(darkthemeimagelistoptions1, darkthemeimagelistoptions2);
            assertEquals(darkthemeimagelistoptions1, darkthemeimagelistoptions1);
            assertFalse(darkthemeimagelistoptions1.equals(null));
            assertNotEquals(darkthemeimagelistoptions3, darkthemeimagelistoptions1);
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }
}
