// This file was generated by the Pelion SDK foundation code generator.
// This is an autogenerated class. Do not modify its content as modifications will be lost at next code generation.
package com.arm.mbed.cloud.sdk.security.model;

import com.arm.mbed.cloud.sdk.annotations.Internal;
import com.arm.mbed.cloud.sdk.annotations.Preamble;
import com.arm.mbed.cloud.sdk.common.Order;
import com.arm.mbed.cloud.sdk.common.listing.IncludeField;
import com.arm.mbed.cloud.sdk.common.listing.ListOptions;
import com.arm.mbed.cloud.sdk.common.listing.filtering.Filter;
import com.arm.mbed.cloud.sdk.common.listing.filtering.Filters;
import java.util.List;

/**
 * Options to use when listing trusted certificates.
 */
@Preamble(description = "Options to use when listing trusted certificates.")
public class TrustedCertificateListOptions extends ListOptions {
    /**
     * Tag for filter by valid.
     */
    public static final String TAG_FILTER_BY_VALID = "valid";

    /**
     * Tag for filter by name.
     */
    public static final String TAG_FILTER_BY_NAME = "name";

    /**
     * Internal constructor.
     * <p>
     * Note: Should not be used. Use {@link #TrustedCertificateListOptions()} instead.
     * 
     * @param pageSize
     *            value.
     * @param maxResults
     *            value.
     * @param order
     *            enumerator value.
     * @param after
     *            value.
     * @param include
     *            value.
     * @param filter
     *            value.
     */
    @Internal
    public TrustedCertificateListOptions(Integer pageSize, Long maxResults, Order order, String after,
                                         List<IncludeField> include, Filters filter) {
        super();
        this.pageSize = pageSize;
        this.maxResults = maxResults;
        this.order = order;
        this.after = after;
        this.include = include;
        this.filter = filter;
    }

    /**
     * Internal constructor.
     * <p>
     * Note: Should not be used. Use {@link #TrustedCertificateListOptions()} instead.
     * 
     * @param trustedCertificateListOptions
     *            a trusted certificate list options.
     */
    @Internal
    public TrustedCertificateListOptions(TrustedCertificateListOptions trustedCertificateListOptions) {
        this();
        setOptions(trustedCertificateListOptions);
    }

    /**
     * Constructor.
     */
    public TrustedCertificateListOptions() {
        super();
        setDefault();
    }

    /**
     * Internal constructor.
     * <p>
     * Note: Should not be used. Use {@link #TrustedCertificateListOptions()} instead.
     * 
     * @param after
     *            value.
     * @param include
     *            value.
     * @param filter
     *            value.
     */
    @Internal
    public TrustedCertificateListOptions(String after, List<IncludeField> include, Filters filter) {
        this(0, 0L, Order.getDefault(), after, include, filter);
    }

    /**
     * Gets all the filters defined on field {@code valid}.
     * 
     * @return All the filters by {@code valid}
     */
    public List<Filter> getValidFilters() {
        return fetchFilters(TAG_FILTER_BY_VALID);
    }

    /**
     * Sets "an equal to" filter by {@code valid}.
     * 
     * @param filterByValid
     *            filter value.
     */
    public void setEqualToValidFilter(boolean filterByValid) {
        addEqualFilter(TAG_FILTER_BY_VALID, filterByValid);
    }

    /**
     * Sets "an equal to" filter by {@code valid}.
     * <p>
     * Similar to
     * {@link com.arm.mbed.cloud.sdk.security.model.TrustedCertificateListOptions#setEqualToValidFilter(boolean)}
     * 
     * @param filterByValid
     *            filter value.
     * @return These list options
     */
    @SuppressWarnings("unchecked")
    public <T extends TrustedCertificateListOptions> T equalToValid(boolean filterByValid) {
        setEqualToValidFilter(filterByValid);
        return (T) this;
    }

    /**
     * Gets all the filters defined on field {@code name}.
     * 
     * @return All the filters by {@code name}
     */
    public List<Filter> getNameFilters() {
        return fetchFilters(TAG_FILTER_BY_NAME);
    }

    /**
     * Sets "an equal to" filter by {@code name}.
     * 
     * @param filterByName
     *            filter value.
     */
    public void setEqualToNameFilter(String filterByName) {
        addEqualFilter(TAG_FILTER_BY_NAME, filterByName);
    }

    /**
     * Sets "an equal to" filter by {@code name}.
     * <p>
     * Similar to
     * {@link com.arm.mbed.cloud.sdk.security.model.TrustedCertificateListOptions#setEqualToNameFilter(String)}
     * 
     * @param filterByName
     *            filter value.
     * @return These list options
     */
    @SuppressWarnings("unchecked")
    public <T extends TrustedCertificateListOptions> T equalToName(String filterByName) {
        setEqualToNameFilter(filterByName);
        return (T) this;
    }

    /**
     * Method to ensure {@link #equals(Object)} is correct.
     * <p>
     * Note: see this article: <a href="https://www.artima.com/lejava/articles/equality.html">canEqual()</a>
     * 
     * @param other
     *            another object.
     * @return true if the other object is an instance of the class in which canEqual is (re)defined, false otherwise.
     */
    protected boolean canEqual(Object other) {
        return other instanceof TrustedCertificateListOptions;
    }

    /**
     * Returns a string representation of the object.
     * <p>
     * 
     * @see java.lang.Object#toString()
     * @return the string representation
     */
    @Override
    public String toString() {
        return "TrustedCertificateListOptions [pageSize=" + pageSize + ", maxResults=" + maxResults + ", order=" + order
               + ", after=" + after + ", include=" + encodeInclude() + ", filter=" + retrieveFilterAsJson() + "]";
    }

    /**
     * Clones this instance.
     * <p>
     * 
     * @see java.lang.Object#clone()
     * @return a cloned instance
     */
    @Override
    public TrustedCertificateListOptions clone() {
        final TrustedCertificateListOptions opt = new TrustedCertificateListOptions();
        opt.setOptions(this);
        return opt;
    }
}
