// This file was generated by the Pelion SDK foundation code generator.
// This is an autogenerated unit test class. Do not modify its content as modifications will be lost at next code generation.
package com.arm.mbed.cloud.sdk.accounts.model;

import static org.junit.Assert.*;

import java.util.Date;
import org.junit.Test;

/**
 * Unit tests for Model UserInvitation.
 */
public class TestUserInvitation {
    /**
     * Tests the clone method.
     */
    @Test
    public void testClone() {
        try {
            UserInvitation userinvitation1 = new UserInvitation("101c316c-f50f-404a-8ca9-1cdd7246ed99",
                                                                new Date(1548165439379L),
                                                                "c98e199e-69a9-4dd1-9190-4f9021f4e5a9",
                                                                new Date(1548165447915L),
                                                                "b0dd3001-3a43-43cc-ba24-987f1de584b0", null,
                                                                new Date(1548165448045L),
                                                                "87e92f5d-624f-4e85-8372-54759fed850c");
            UserInvitation userinvitation2 = userinvitation1.clone();
            assertNotNull(userinvitation1);
            assertNotNull(userinvitation2);
            assertNotSame(userinvitation2, userinvitation1);
            assertEquals(userinvitation2, userinvitation1);
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }

    /**
     * Tests the hashCode method.
     */
    @Test
    public void testHashCode() {
        try {
            UserInvitation userinvitation1 = new UserInvitation("1e725f8c-870f-4dbd-8781-0f782c3f7e3f",
                                                                new Date(1548165440012L),
                                                                "ea101f1a-4063-4add-9fef-05bdcede274b",
                                                                new Date(1548165439035L),
                                                                "98a1ddda-f2ce-4491-b894-4ca8ba7fa671", null,
                                                                new Date(1548165444993L),
                                                                "9608e5d4-ba78-4d97-b8af-d64653b2667a");
            UserInvitation userinvitation2 = new UserInvitation("1e725f8c-870f-4dbd-8781-0f782c3f7e3f",
                                                                new Date(1548165440012L),
                                                                "ea101f1a-4063-4add-9fef-05bdcede274b",
                                                                new Date(1548165439035L),
                                                                "98a1ddda-f2ce-4491-b894-4ca8ba7fa671", null,
                                                                new Date(1548165444993L),
                                                                "9608e5d4-ba78-4d97-b8af-d64653b2667a");
            assertNotNull(userinvitation1);
            assertNotNull(userinvitation2);
            assertNotSame(userinvitation2, userinvitation1);
            assertEquals(userinvitation2, userinvitation1);
            assertEquals(userinvitation2.hashCode(), userinvitation1.hashCode());
            int hashCode = userinvitation1.hashCode();
            for (int i = 0; i < 5; i++) {
                assertEquals(hashCode, userinvitation1.hashCode());
            }
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }

    /**
     * Tests the isValid method.
     */
    @Test
    public void testIsValid() {
        UserInvitation userinvitation = new UserInvitation("dad730e7-92b0-4b2a-812d-a033549352da",
                                                           new Date(1548165441121L),
                                                           "82a979f7-cf79-402d-9d0b-2feb3d2f5317",
                                                           new Date(1548165440626L),
                                                           "724f9946-60ae-4bc9-9aa9-c42193f37669", null,
                                                           new Date(1548165444546L),
                                                           "c8193717-2bc1-47d0-88a9-6b7074091b34");
        assertTrue(userinvitation.isValid());
        UserInvitation userinvitationInvalid = new UserInvitation("3e6ee9df-461f-4c32-aa3e-51fddee7ba9c",
                                                                  new Date(1548165442359L), null,
                                                                  new Date(1548165446397L),
                                                                  "733081fa-c307-4d85-8078-87decc4aca71", null,
                                                                  new Date(1548165445783L),
                                                                  "3bd74139-15ec-459c-bd6e-ba4834b4e786");
        assertFalse(userinvitationInvalid.isValid());
    }

    /**
     * Tests the equals method.
     */
    @Test
    public void testEquals() {
        try {
            UserInvitation userinvitation1 = new UserInvitation("d4b6e3eb-dab8-43ef-b79a-10a754fcd894",
                                                                new Date(1548165445236L),
                                                                "fa3302c3-4444-45a9-b75c-18db73cfaad6",
                                                                new Date(1548165441762L),
                                                                "e7f5ba19-0605-435d-8764-9a77545316f2", null,
                                                                new Date(1548165441148L),
                                                                "bbb36b61-ab43-4877-8a67-799da360947c");
            UserInvitation userinvitation2 = new UserInvitation("d4b6e3eb-dab8-43ef-b79a-10a754fcd894",
                                                                new Date(1548165445236L),
                                                                "fa3302c3-4444-45a9-b75c-18db73cfaad6",
                                                                new Date(1548165441762L),
                                                                "e7f5ba19-0605-435d-8764-9a77545316f2", null,
                                                                new Date(1548165441148L),
                                                                "bbb36b61-ab43-4877-8a67-799da360947c");
            UserInvitation userinvitation3 = new UserInvitation("06c191c9-9724-4493-bd1c-dcf2d84cd6ad",
                                                                new Date(1548165440950L),
                                                                "7a8c554f-b60c-4483-883b-82bcd4488835",
                                                                new Date(1548165440968L),
                                                                "b8afbd41-cd8c-4019-bf05-9a408906634f", null,
                                                                new Date(1548165446091L),
                                                                "09588178-4407-46e6-ac4f-ef809806596a");
            assertNotNull(userinvitation1);
            assertNotNull(userinvitation2);
            assertNotNull(userinvitation3);
            assertNotSame(userinvitation2, userinvitation1);
            assertNotSame(userinvitation3, userinvitation1);
            assertEquals(userinvitation2, userinvitation1);
            assertEquals(userinvitation2, userinvitation1);
            assertEquals(userinvitation1, userinvitation2);
            assertEquals(userinvitation1, userinvitation1);
            assertFalse(userinvitation1.equals(null));
            assertNotEquals(userinvitation3, userinvitation1);
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }
}
