// This file was generated by the Pelion SDK foundation code generator.
// This model class was autogenerated on Wed Jan 06 18:10:54 CST 2021. Feel free to change its contents as you wish.
// TODO The following fields need to be defined:
// - isDeveloperCertificate
package com.arm.mbed.cloud.sdk.security.model;

import com.arm.mbed.cloud.sdk.annotations.Internal;
import com.arm.mbed.cloud.sdk.annotations.NotImplemented;
import com.arm.mbed.cloud.sdk.annotations.Preamble;
import com.arm.mbed.cloud.sdk.common.NotImplementedException;
import java.util.Date;

/**
 * Model for a subtenant trusted certificate.
 */
@Preamble(description = "Model for a subtenant trusted certificate.")
@SuppressWarnings("PMD.CyclomaticComplexity")
public class SubtenantTrustedCertificate extends AbstractSubtenantTrustedCertificate {
    /**
     * Serialisation Id.
     */
    private static final long serialVersionUID = 8306879121921220L;
    private boolean isDeveloperCertificate;

    /**
     * Internal constructor.
     * 
     * <p>
     * Constructor based on all fields.
     * <p>
     * Note: Should not be used. Use {@link #SubtenantTrustedCertificate()} instead.
     * 
     * @param isDeveloperCertificate
     *            Whether or not this certificate is a developer certificate.
     * @param accountId
     *            The ID of the account.
     * @param certificate
     *            X509.v3 trusted certificate in PEM format.
     * @param certificateFingerprint
     *            A SHA-256 fingerprint of the certificate.
     * @param createdAt
     *            Creation UTC time RFC3339.
     * @param description
     *            Human readable description of this certificate.
     * @param deviceExecutionMode
     *            Device execution mode where 1 means a developer certificate.
     * @param enrollmentMode
     *            DEPRECATED: Certificate is used in enrollment mode. Default value is false.
     * @param id
     *            Entity ID.
     * @param issuer
     *            Issuer of the certificate.
     * @param name
     *            Certificate name.
     * @param ownerId
     *            The ID of the owner.
     * @param service
     *            Service name where the certificate is used.
     * @param status
     *            Status of the certificate.
     * @param subject
     *            Subject of the certificate.
     * @param updatedAt
     *            Last update UTC time RFC3339.
     * @param valid
     *            This read-only flag indicates whether the certificate is valid or not.
     * @param validity
     *            Expiration time in UTC formatted as RFC3339.
     */
    @Internal
    @SuppressWarnings("PMD.CyclomaticComplexity")
    public SubtenantTrustedCertificate(String accountId, String certificate, String certificateFingerprint,
                                       Date createdAt, String description, int deviceExecutionMode,
                                       boolean enrollmentMode, String id, boolean isDeveloperCertificate, String issuer,
                                       String name, String ownerId, SubtenantTrustedCertificateService service,
                                       SubtenantTrustedCertificateStatus status, String subject, Date updatedAt,
                                       boolean valid, Date validity) {
        super(accountId, certificate, certificateFingerprint, createdAt, description, deviceExecutionMode,
              enrollmentMode, id, issuer, name, ownerId, service, status, subject, updatedAt, valid, validity);
        this.isDeveloperCertificate = isDeveloperCertificate;
    }

    /**
     * Internal constructor.
     * 
     * <p>
     * Constructor based on a similar object.
     * <p>
     * Note: Should not be used. Use {@link #SubtenantTrustedCertificate()} instead.
     * 
     * @param subtenantTrustedCertificate
     *            a subtenant trusted certificate.
     */
    @SuppressWarnings("deprecation")
    @Internal
    public SubtenantTrustedCertificate(SubtenantTrustedCertificate subtenantTrustedCertificate) {
        this(subtenantTrustedCertificate == null ? (String) null : subtenantTrustedCertificate.accountId,
             subtenantTrustedCertificate == null ? (String) null : subtenantTrustedCertificate.certificate,
             subtenantTrustedCertificate == null ? (String) null : subtenantTrustedCertificate.certificateFingerprint,
             subtenantTrustedCertificate == null ? new Date() : subtenantTrustedCertificate.createdAt,
             subtenantTrustedCertificate == null ? (String) null : subtenantTrustedCertificate.description,
             subtenantTrustedCertificate == null ? 0 : subtenantTrustedCertificate.deviceExecutionMode,
             subtenantTrustedCertificate != null && subtenantTrustedCertificate.enrollmentMode,
             subtenantTrustedCertificate == null ? (String) null : subtenantTrustedCertificate.id,
             subtenantTrustedCertificate != null && subtenantTrustedCertificate.isDeveloperCertificate(),
             subtenantTrustedCertificate == null ? (String) null : subtenantTrustedCertificate.issuer,
             subtenantTrustedCertificate == null ? (String) null : subtenantTrustedCertificate.name,
             subtenantTrustedCertificate == null ? (String) null : subtenantTrustedCertificate.ownerId,
             subtenantTrustedCertificate == null ? SubtenantTrustedCertificateService.getDefault()
                                                 : subtenantTrustedCertificate.service,
             subtenantTrustedCertificate == null ? SubtenantTrustedCertificateStatus.getDefault()
                                                 : subtenantTrustedCertificate.status,
             subtenantTrustedCertificate == null ? (String) null : subtenantTrustedCertificate.subject,
             subtenantTrustedCertificate == null ? new Date() : subtenantTrustedCertificate.updatedAt,
             subtenantTrustedCertificate != null && subtenantTrustedCertificate.valid,
             subtenantTrustedCertificate == null ? new Date() : subtenantTrustedCertificate.validity);
    }

    /**
     * Constructor.
     */
    public SubtenantTrustedCertificate() {
        this((String) null, (String) null, (String) null, new Date(), (String) null, 0, false, (String) null, false,
             (String) null, (String) null, (String) null, SubtenantTrustedCertificateService.getDefault(),
             SubtenantTrustedCertificateStatus.getDefault(), (String) null, new Date(), false, new Date());
    }

    @Internal
    public SubtenantTrustedCertificate(String accountId, String certificate, String certificateFingerprint,
                                       Date createdAt, String description, int deviceExecutionMode,
                                       boolean enrollmentMode, String id, String issuer, String name, String ownerId,
                                       SubtenantTrustedCertificateService service,
                                       SubtenantTrustedCertificateStatus status, String subject, Date updatedAt,
                                       boolean valid, Date validity) {
        super(accountId, certificate, certificateFingerprint, createdAt, description, deviceExecutionMode,
              enrollmentMode, id, issuer, name, ownerId, service, status, subject, updatedAt, valid, validity);
    }

    /**
     * Constructor.
     * 
     * <p>
     * Constructor based on object identifier.
     * <p>
     * 
     * @param id
     *            Entity ID.
     */
    public SubtenantTrustedCertificate(String id) {
        this();
        setId(id);
    }

    /**
     * Internal constructor.
     * 
     * <p>
     * Constructor based on read-only fields.
     * <p>
     * Note: Should not be used. Use {@link #SubtenantTrustedCertificate()} instead.
     * 
     * @param isDeveloperCertificate
     *            Whether or not this certificate is a developer certificate.
     * @param certificateFingerprint
     *            A SHA-256 fingerprint of the certificate.
     * @param createdAt
     *            Creation UTC time RFC3339.
     * @param deviceExecutionMode
     *            Device execution mode where 1 means a developer certificate.
     * @param issuer
     *            Issuer of the certificate.
     * @param ownerId
     *            The ID of the owner.
     * @param subject
     *            Subject of the certificate.
     * @param updatedAt
     *            Last update UTC time RFC3339.
     * @param valid
     *            This read-only flag indicates whether the certificate is valid or not.
     * @param validity
     *            Expiration time in UTC formatted as RFC3339.
     */
    @Internal
    @SuppressWarnings("PMD.CyclomaticComplexity")
    public SubtenantTrustedCertificate(String certificateFingerprint, Date createdAt, int deviceExecutionMode,
                                       boolean isDeveloperCertificate, String issuer, String ownerId, String subject,
                                       Date updatedAt, boolean valid, Date validity) {
        this((String) null, (String) null, certificateFingerprint, createdAt, (String) null, deviceExecutionMode, false,
             (String) null, isDeveloperCertificate, issuer, (String) null, ownerId,
             SubtenantTrustedCertificateService.getDefault(), SubtenantTrustedCertificateStatus.getDefault(), subject,
             updatedAt, valid, validity);
    }

    /**
     * Constructor.
     * 
     * <p>
     * Constructor based on required fields.
     * <p>
     * 
     * @param accountId
     *            The ID of the account.
     * @param certificate
     *            X509.v3 trusted certificate in PEM format.
     * @param name
     *            Certificate name.
     * @param service
     *            Service name where the certificate is used.
     */
    public SubtenantTrustedCertificate(String accountId, String certificate, String name,
                                       SubtenantTrustedCertificateService service) {
        this(accountId, certificate, (String) null, new Date(), (String) null, 0, false, (String) null, false,
             (String) null, name, (String) null, service, SubtenantTrustedCertificateStatus.getDefault(), (String) null,
             new Date(), false, new Date());
    }

    /**
     * Gets whether or not this certificate is a developer certificate.
     * 
     * @return isDeveloperCertificate
     */
    @NotImplemented
    public boolean isDeveloperCertificate() throws NotImplementedException {
        return isDeveloperCertificate;
    }

    /**
     * Returns a string representation of the object.
     * 
     * <p>
     * 
     * @see java.lang.Object#toString()
     * @return the string representation
     */
    @SuppressWarnings("deprecation")
    @Override
    public String toString() {
        return "SubtenantTrustedCertificate [isDeveloperCertificate=" + isDeveloperCertificate() + ", accountId="
               + accountId + ", certificate=" + certificate + ", certificateFingerprint=" + certificateFingerprint
               + ", createdAt=" + createdAt + ", description=" + description + ", deviceExecutionMode="
               + deviceExecutionMode + ", enrollmentMode=" + enrollmentMode + ", id=" + id + ", issuer=" + issuer
               + ", name=" + name + ", ownerId=" + ownerId + ", service=" + service + ", status=" + status
               + ", subject=" + subject + ", updatedAt=" + updatedAt + ", valid=" + valid + ", validity=" + validity
               + "]";
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + (isDeveloperCertificate ? 1231 : 1237);
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!super.equals(obj)) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final SubtenantTrustedCertificate other = (SubtenantTrustedCertificate) obj;
        if (isDeveloperCertificate != other.isDeveloperCertificate) {
            return false;
        }
        return true;
    }

    /**
     * Clones this instance.
     * 
     * <p>
     * 
     * @see java.lang.Object#clone()
     * @return a cloned instance
     */
    @Override
    public SubtenantTrustedCertificate clone() {
        return new SubtenantTrustedCertificate(this);
    }

    /**
     * Method to ensure {@link #equals(Object)} is correct.
     * 
     * <p>
     * Note: see this article: <a href="https://www.artima.com/lejava/articles/equality.html">canEqual()</a>
     * 
     * @param other
     *            another object.
     * @return true if the other object is an instance of the class in which canEqual is (re)defined, false otherwise.
     */
    @Override
    protected boolean canEqual(Object other) {
        return other instanceof SubtenantTrustedCertificate;
    }

}
