// This file was generated by the Pelion SDK foundation code generator.
// This is an autogenerated unit test class. Do not modify its content as modifications will be lost at next code generation.
package com.arm.mbed.cloud.sdk.devices.model;

import static org.junit.Assert.*;

import org.junit.Test;

/**
 * Unit tests for Model DeviceEvents.
 */
public class TestDeviceEvents {
    /**
     * Tests the clone method.
     */
    @Test
    public void testClone() {
        DeviceEvents deviceevents1 = new DeviceEvents(null, new java.util.Date(1545943214530L), null,
                                                      new java.util.Date(1545943213477L),
                                                      "56512535-925f-4752-8e1a-807faaf91bc7",
                                                      "39b2a038-2bf1-413b-a956-87b919083f36",
                                                      "1f546792-cf43-4864-8b04-39c954dec9a8",
                                                      "bf480fc5-a71a-44e4-a131-8946bbed6af3",
                                                      "f32df7c2-3bb1-43a3-b9d7-7f46d550269b",
                                                      "91d6f5ee-36f5-44f5-a183-22ab98e52052", true);
        DeviceEvents deviceevents2 = deviceevents1.clone();
        assertNotNull(deviceevents1);
        assertNotNull(deviceevents2);
        assertNotSame(deviceevents2, deviceevents1);
        assertEquals(deviceevents2, deviceevents1);
    }

    /**
     * Tests the isvalid method.
     */
    @Test
    public void testIsvalid() {
        DeviceEvents deviceevents = new DeviceEvents(null, new java.util.Date(1545943218883L), null,
                                                     new java.util.Date(1545943218854L),
                                                     "120e9719-ad89-49f4-8fbc-feaa0fd3bd7d",
                                                     "4c7c73d9-bbb8-406e-bf3e-c426283fec5e",
                                                     "17ac6fd4-e15f-4d44-9f14-30eec7ee636a",
                                                     "1601a3b1-fcea-4043-b96e-9d2809a864d3",
                                                     "651da27e-977b-4cf3-a39d-34a71ea9ed22",
                                                     "fe2243c1-c16a-49ce-8df0-eb3e01eed411", false);
        assertTrue(deviceevents.isValid());
    }

    /**
     * Tests the hashcode method.
     */
    @Test
    public void testHashcode() {
        DeviceEvents deviceevents1 = new DeviceEvents(null, new java.util.Date(1545943220196L), null,
                                                      new java.util.Date(1545943217382L),
                                                      "59964c65-13ea-4547-8090-ab05363d7faf",
                                                      "4cc219f5-6c13-45db-9f7f-4c8c1898d343",
                                                      "d42c0a72-9bfd-4cfe-b26a-bbeb678bcd57",
                                                      "f7282cc0-e750-4e4b-acb3-5fd327fadb8d",
                                                      "34c516e6-6fef-41f5-99b9-36d090b8937e",
                                                      "bf92e636-b857-48b9-be36-8b747d008164", false);
        DeviceEvents deviceevents2 = new DeviceEvents(null, new java.util.Date(1545943220196L), null,
                                                      new java.util.Date(1545943217382L),
                                                      "59964c65-13ea-4547-8090-ab05363d7faf",
                                                      "4cc219f5-6c13-45db-9f7f-4c8c1898d343",
                                                      "d42c0a72-9bfd-4cfe-b26a-bbeb678bcd57",
                                                      "f7282cc0-e750-4e4b-acb3-5fd327fadb8d",
                                                      "34c516e6-6fef-41f5-99b9-36d090b8937e",
                                                      "bf92e636-b857-48b9-be36-8b747d008164", false);
        assertNotNull(deviceevents1);
        assertNotNull(deviceevents2);
        assertNotSame(deviceevents2, deviceevents1);
        assertEquals(deviceevents2, deviceevents1);
        assertEquals(deviceevents2.hashCode(), deviceevents1.hashCode());
        int hashCode = deviceevents1.hashCode();
        for (int i = 0; i < 5; i++) {
            assertEquals(hashCode, deviceevents1.hashCode());
        }
    }

    /**
     * Tests the equals method.
     */
    @Test
    public void testEquals() {
        DeviceEvents deviceevents1 = new DeviceEvents(null, new java.util.Date(1545943214017L), null,
                                                      new java.util.Date(1545943215184L),
                                                      "609b6d6d-a6ac-4747-a3d0-651e54c34a16",
                                                      "26ee398a-1c71-40d2-bbca-bf1497405b21",
                                                      "d5ed75d4-1401-40f4-a830-b321b21a4723",
                                                      "cc5d5506-aaf6-4613-b882-dd90eef39b24",
                                                      "981867de-fa11-428e-95c1-271dff4f152c",
                                                      "c9bd5fc8-b9e2-41c4-bb52-b9e4861980de", false);
        DeviceEvents deviceevents2 = new DeviceEvents(null, new java.util.Date(1545943214017L), null,
                                                      new java.util.Date(1545943215184L),
                                                      "609b6d6d-a6ac-4747-a3d0-651e54c34a16",
                                                      "26ee398a-1c71-40d2-bbca-bf1497405b21",
                                                      "d5ed75d4-1401-40f4-a830-b321b21a4723",
                                                      "cc5d5506-aaf6-4613-b882-dd90eef39b24",
                                                      "981867de-fa11-428e-95c1-271dff4f152c",
                                                      "c9bd5fc8-b9e2-41c4-bb52-b9e4861980de", false);
        DeviceEvents deviceevents3 = new DeviceEvents(null, new java.util.Date(1545943218122L), null,
                                                      new java.util.Date(1545943216528L),
                                                      "8de00074-db26-4447-b0f4-877e08c63d2b",
                                                      "a4c3960d-9f1c-4da6-a1c0-c00004965087",
                                                      "d2a961e7-ca0a-4dbb-9a20-fa8bfd2b3a53",
                                                      "09b542eb-41e1-4392-85f2-cd408f8f7c35",
                                                      "a32b1c6b-84b7-42ae-ab10-8d6939cc3a47",
                                                      "6330b0bd-3dfe-4a52-a140-398f0cc1da63", false);
        assertNotNull(deviceevents1);
        assertNotNull(deviceevents2);
        assertNotNull(deviceevents3);
        assertNotSame(deviceevents2, deviceevents1);
        assertNotSame(deviceevents3, deviceevents1);
        assertEquals(deviceevents2, deviceevents1);
        assertEquals(deviceevents2, deviceevents1);
        assertEquals(deviceevents1, deviceevents2);
        assertEquals(deviceevents1, deviceevents1);
        assertFalse(deviceevents1.equals(null));
        assertNotEquals(deviceevents3, deviceevents1);
    }
}
