// This file was generated by the Pelion SDK foundation code generator.
// This is an autogenerated unit test class. Do not modify its content as modifications will be lost at next code generation.
package com.arm.mbed.cloud.sdk.devices.model;

import static org.junit.Assert.*;

import org.junit.Test;

/**
 * Unit tests for Model Device.
 */
public class TestDevice {
    /**
     * Tests the clone method.
     */
    @Test
    public void testClone() {
        Device device1 = new Device("8ace93d4-034c-4573-a288-c15b6650cd17", true, new java.util.Date(1545943220425L),
                                    new java.util.Date(1545943219484L), "7b19e205-984c-4839-a700-46ba371125bf",
                                    new java.util.Date(1545943217094L), new java.util.Date(1545943214470L), null,
                                    com.arm.mbed.cloud.sdk.devices.model.DeviceDeployedState.getDefault(),
                                    "43d44d4c-8ad3-43ea-bfc8-f12b8ba60df3", "d0727aed-d054-4334-90c7-d071dfb2a7c0",
                                    "a75d7e06-7f0d-4afc-90f5-437aa2f4d7bf", 113, "d41d1d94-bda5-49be-9b0f-73519c3bd180",
                                    "1863d0a5-f962-448b-bc8e-e261fa168447", "a3ca6114-c6c0-47c7-abd1-fc654666cf5c",
                                    new java.util.Date(1545943213026L), "ea4887eb-0700-4719-8d7b-02206e00e163",
                                    "068eed5f-ebb1-4f1a-aa2a-0435aaa57d7b", "af2dbb0e-d89f-4b46-9e3a-5a051c37da47",
                                    "354c717a-0cca-4b95-9154-19205b927561", new java.util.Date(1545943219949L),
                                    com.arm.mbed.cloud.sdk.devices.model.DeviceMechanism.getDefault(),
                                    "cf150ee4-f371-4dc8-80ac-a6354aa318b6", "a094fbcb-fa82-4a14-90c2-90c6d0364fc3",
                                    "158e511b-ceff-42f5-930e-d4c9cd13117e",
                                    com.arm.mbed.cloud.sdk.devices.model.DeviceState.getDefault(),
                                    new java.util.Date(1545943219233L), "a3c61c76-ae0f-4b26-8a4f-f0acafd64b77");
        Device device2 = device1.clone();
        assertNotNull(device1);
        assertNotNull(device2);
        assertNotSame(device2, device1);
        assertEquals(device2, device1);
    }

    /**
     * Tests the isvalid method.
     */
    @Test
    public void testIsvalid() {
        Device device = new Device("9e017445-9fca-4bb6-827d-4c1c11ab368e", false, new java.util.Date(1545943219977L),
                                   new java.util.Date(1545943216694L), "37f63fd6-9f3f-4778-baf3-57265931e7b1",
                                   new java.util.Date(1545943216105L), new java.util.Date(1545943212452L), null,
                                   com.arm.mbed.cloud.sdk.devices.model.DeviceDeployedState.getDefault(),
                                   "966da0fd-9122-4be3-a6a4-cbe42c27739a", "b811de11-1819-43f9-843a-6550ee98faf1",
                                   "f2c41828-a3ad-4c1d-be10-943f78589c3d", -2, "4f5a130e-9b12-40f5-a44a-fd75dec647ae",
                                   "63f8dcb2-3526-4e62-a563-2601962ab5d0", "145863cf-2bf0-460c-ae5e-8e335f020840",
                                   new java.util.Date(1545943212873L), "b95c0e7c-eef2-45a1-85b2-5bc6c0e2bf77",
                                   "b9b66428-a1cd-4919-b79c-d440a4005d22", "a067c772-742f-49e2-b96f-f1c09174f3f9",
                                   "8f923f19-701f-4c17-a132-bd5ff2654ca1", new java.util.Date(1545943211889L),
                                   com.arm.mbed.cloud.sdk.devices.model.DeviceMechanism.getDefault(),
                                   "05cab62e-c331-4f08-be54-e5e9e7215570", "dfb1d278-73f2-427c-95d9-eb35f48abb34",
                                   "32f72514-99ed-4cfb-8b33-10e35538bd43",
                                   com.arm.mbed.cloud.sdk.devices.model.DeviceState.getDefault(),
                                   new java.util.Date(1545943214600L), "fb7a2272-9cce-4b6e-9ab2-1ad128929d43");
        assertTrue(device.isValid());
    }

    /**
     * Tests the hashcode method.
     */
    @Test
    public void testHashcode() {
        Device device1 = new Device("1b778b98-5dd9-4d8b-b32b-1500271a28d7", false, new java.util.Date(1545943212445L),
                                    new java.util.Date(1545943215288L), "d1c29245-d757-4a00-9db7-b8399c62f005",
                                    new java.util.Date(1545943215127L), new java.util.Date(1545943212140L), null,
                                    com.arm.mbed.cloud.sdk.devices.model.DeviceDeployedState.getDefault(),
                                    "371ed9aa-cdcd-4b10-9931-07ab15455334", "908402d8-18c5-44be-b361-eb1a34f9c759",
                                    "0b766954-4a76-45b9-a08b-f34109b708cb", 58, "a086d999-a904-4f7e-88fa-cb48e4696c21",
                                    "6df300de-ade9-4427-aac4-2572ab3fbd23", "b48636f2-3bb8-4069-a9ac-fe7da557880c",
                                    new java.util.Date(1545943219898L), "009883c6-c1ba-4c14-a0e2-844475566b3a",
                                    "b8eee784-36fe-4fa0-8547-38a2a9e07b50", "9d387066-b1d0-48af-a78d-944cd6770149",
                                    "4fe18822-f9ed-4bf9-98b8-0d6e6a409ea3", new java.util.Date(1545943215421L),
                                    com.arm.mbed.cloud.sdk.devices.model.DeviceMechanism.getDefault(),
                                    "1a1da5dd-0eec-420b-9e66-3e565d219da3", "356d7bdf-b6c4-4f1e-bed2-26d639ba1f0d",
                                    "8391e84b-f984-418a-8a00-2ecfbdf9da2e",
                                    com.arm.mbed.cloud.sdk.devices.model.DeviceState.getDefault(),
                                    new java.util.Date(1545943213108L), "fc7776dd-1d4d-4e4c-ab94-3c8a22d07755");
        Device device2 = new Device("1b778b98-5dd9-4d8b-b32b-1500271a28d7", false, new java.util.Date(1545943212445L),
                                    new java.util.Date(1545943215288L), "d1c29245-d757-4a00-9db7-b8399c62f005",
                                    new java.util.Date(1545943215127L), new java.util.Date(1545943212140L), null,
                                    com.arm.mbed.cloud.sdk.devices.model.DeviceDeployedState.getDefault(),
                                    "371ed9aa-cdcd-4b10-9931-07ab15455334", "908402d8-18c5-44be-b361-eb1a34f9c759",
                                    "0b766954-4a76-45b9-a08b-f34109b708cb", 58, "a086d999-a904-4f7e-88fa-cb48e4696c21",
                                    "6df300de-ade9-4427-aac4-2572ab3fbd23", "b48636f2-3bb8-4069-a9ac-fe7da557880c",
                                    new java.util.Date(1545943219898L), "009883c6-c1ba-4c14-a0e2-844475566b3a",
                                    "b8eee784-36fe-4fa0-8547-38a2a9e07b50", "9d387066-b1d0-48af-a78d-944cd6770149",
                                    "4fe18822-f9ed-4bf9-98b8-0d6e6a409ea3", new java.util.Date(1545943215421L),
                                    com.arm.mbed.cloud.sdk.devices.model.DeviceMechanism.getDefault(),
                                    "1a1da5dd-0eec-420b-9e66-3e565d219da3", "356d7bdf-b6c4-4f1e-bed2-26d639ba1f0d",
                                    "8391e84b-f984-418a-8a00-2ecfbdf9da2e",
                                    com.arm.mbed.cloud.sdk.devices.model.DeviceState.getDefault(),
                                    new java.util.Date(1545943213108L), "fc7776dd-1d4d-4e4c-ab94-3c8a22d07755");
        assertNotNull(device1);
        assertNotNull(device2);
        assertNotSame(device2, device1);
        assertEquals(device2, device1);
        assertEquals(device2.hashCode(), device1.hashCode());
        int hashCode = device1.hashCode();
        for (int i = 0; i < 5; i++) {
            assertEquals(hashCode, device1.hashCode());
        }
    }

    /**
     * Tests the equals method.
     */
    @Test
    public void testEquals() {
        Device device1 = new Device("5dd01ff7-ab6c-4f4f-a4e3-e6a15db57001", true, new java.util.Date(1545943213260L),
                                    new java.util.Date(1545943211993L), "2c37f7ee-ed1a-43fa-89a5-e1be5d0a75fa",
                                    new java.util.Date(1545943213087L), new java.util.Date(1545943213645L), null,
                                    com.arm.mbed.cloud.sdk.devices.model.DeviceDeployedState.getDefault(),
                                    "73c790f9-862b-4282-9fd9-3017b535ab3d", "e3c986f1-379b-44bc-84ca-b88ab0158bba",
                                    "5c6db596-95f1-48d4-8f8f-101467b0c5de", -97, "a1738995-a80b-4eb6-b779-30b1a50644d7",
                                    "de046668-f5db-42dd-ada0-b798aefc6b61", "f183f409-eb6b-40c6-8369-9de05807d583",
                                    new java.util.Date(1545943219902L), "a7c80511-2d28-4154-ac14-873aae398d9d",
                                    "a70ad691-ba8b-4ee0-9224-91ab6049e3ed", "82067e8e-0ed6-41ba-915c-02af21380dab",
                                    "94641812-5364-40cc-b249-87c70a82eb38", new java.util.Date(1545943220098L),
                                    com.arm.mbed.cloud.sdk.devices.model.DeviceMechanism.getDefault(),
                                    "f3347a9e-b853-444e-b402-642cf7f97c57", "478ed0c4-05ca-4adc-9d8e-10c10ba19a2b",
                                    "68f08d68-e02c-462e-8f5a-c7e500c4ae53",
                                    com.arm.mbed.cloud.sdk.devices.model.DeviceState.getDefault(),
                                    new java.util.Date(1545943216185L), "35b0fe38-bcbc-41a8-8193-5d844615b409");
        Device device2 = new Device("5dd01ff7-ab6c-4f4f-a4e3-e6a15db57001", true, new java.util.Date(1545943213260L),
                                    new java.util.Date(1545943211993L), "2c37f7ee-ed1a-43fa-89a5-e1be5d0a75fa",
                                    new java.util.Date(1545943213087L), new java.util.Date(1545943213645L), null,
                                    com.arm.mbed.cloud.sdk.devices.model.DeviceDeployedState.getDefault(),
                                    "73c790f9-862b-4282-9fd9-3017b535ab3d", "e3c986f1-379b-44bc-84ca-b88ab0158bba",
                                    "5c6db596-95f1-48d4-8f8f-101467b0c5de", -97, "a1738995-a80b-4eb6-b779-30b1a50644d7",
                                    "de046668-f5db-42dd-ada0-b798aefc6b61", "f183f409-eb6b-40c6-8369-9de05807d583",
                                    new java.util.Date(1545943219902L), "a7c80511-2d28-4154-ac14-873aae398d9d",
                                    "a70ad691-ba8b-4ee0-9224-91ab6049e3ed", "82067e8e-0ed6-41ba-915c-02af21380dab",
                                    "94641812-5364-40cc-b249-87c70a82eb38", new java.util.Date(1545943220098L),
                                    com.arm.mbed.cloud.sdk.devices.model.DeviceMechanism.getDefault(),
                                    "f3347a9e-b853-444e-b402-642cf7f97c57", "478ed0c4-05ca-4adc-9d8e-10c10ba19a2b",
                                    "68f08d68-e02c-462e-8f5a-c7e500c4ae53",
                                    com.arm.mbed.cloud.sdk.devices.model.DeviceState.getDefault(),
                                    new java.util.Date(1545943216185L), "35b0fe38-bcbc-41a8-8193-5d844615b409");
        Device device3 = new Device("001c34b8-7edd-49da-93cd-a85d62f9c4a4", true, new java.util.Date(1545943216042L),
                                    new java.util.Date(1545943211910L), "6f650311-7aaa-48b2-81b8-455475b10556",
                                    new java.util.Date(1545943212256L), new java.util.Date(1545943212026L), null,
                                    com.arm.mbed.cloud.sdk.devices.model.DeviceDeployedState.getDefault(),
                                    "a963ff33-814d-4913-94de-fac592831841", "7329529c-6f0e-4335-af78-9ad55a08dd98",
                                    "41e96382-24fb-4337-94db-2a508fc38373", 63, "3d0e6224-192a-4a6e-be8c-c55882e43827",
                                    "f316abc0-5dd1-456e-a0a0-f01a39b64dee", "7a7a3558-0da4-4f05-8aff-242d0b0a9c7d",
                                    new java.util.Date(1545943216043L), "360f504f-be46-4eff-9b9f-405a145581f8",
                                    "54d1c6a7-4fc4-41c9-8403-af722888ff6a", "4a1de965-495e-496e-b0eb-0a9278120e88",
                                    "132a67de-4341-410b-8c1b-5bf67f336b40", new java.util.Date(1545943218700L),
                                    com.arm.mbed.cloud.sdk.devices.model.DeviceMechanism.getDefault(),
                                    "1ece745a-880d-4558-8ee2-9a2eef9acb0d", "32260078-d8f1-4b17-8a81-90f8b3dd6880",
                                    "d8083661-94cb-40b7-b12c-9c188d1db240",
                                    com.arm.mbed.cloud.sdk.devices.model.DeviceState.getDefault(),
                                    new java.util.Date(1545943213994L), "9d90bd88-3498-4cd7-9654-3f12994b47ef");
        assertNotNull(device1);
        assertNotNull(device2);
        assertNotNull(device3);
        assertNotSame(device2, device1);
        assertNotSame(device3, device1);
        assertEquals(device2, device1);
        assertEquals(device2, device1);
        assertEquals(device1, device2);
        assertEquals(device1, device1);
        assertFalse(device1.equals(null));
        assertNotEquals(device3, device1);
    }
}
