// This file was generated by the Pelion SDK foundation code generator.
// This is an autogenerated unit test class. Do not modify its content as modifications will be lost at next code generation.
package com.arm.mbed.cloud.sdk.deviceupdate.model;

import static org.junit.Assert.*;

import java.util.Date;
import org.junit.Test;

/**
 * Unit tests for Model CampaignStatisticsEvents.
 */
@SuppressWarnings("PMD.AvoidDuplicateLiterals")
public class TestCampaignStatisticsEvents {
    /**
     * Tests the clone method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testClone() {
        try {
            CampaignStatisticsEvents campaignstatisticsevents1 = new CampaignStatisticsEvents("70d0dcf6-50a1-414c-9eee-a4241b2eae83",
                                                                                              -49,
                                                                                              new Date(1561989471552L),
                                                                                              "547f1a4c-ff5d-4c64-b602-effe2e95da61",
                                                                                              "d667e84e-d0f9-4176-b38e-91655bacd7bb",
                                                                                              "e44c886f-0657-4975-b193-79c84237c985",
                                                                                              "f4145492-0b2b-4ac1-91d3-7850fd1079a1",
                                                                                              "747dc3a7-09fe-41ea-b09c-75be6723d14c");
            CampaignStatisticsEvents campaignstatisticsevents2 = campaignstatisticsevents1.clone();
            assertNotNull(campaignstatisticsevents1);
            assertNotNull(campaignstatisticsevents2);
            assertNotSame(campaignstatisticsevents2, campaignstatisticsevents1);
            assertEquals(campaignstatisticsevents2, campaignstatisticsevents1);
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }

    /**
     * Tests the hashCode method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testHashCode() {
        try {
            CampaignStatisticsEvents campaignstatisticsevents1 = new CampaignStatisticsEvents("fe3707e3-bf48-48a0-b10e-cadf5408c5cb",
                                                                                              -38,
                                                                                              new Date(1561989476578L),
                                                                                              "655283ee-528f-444e-a96f-00a3b214c702",
                                                                                              "ae05f70c-fcfd-44e3-8a74-57ed7abbf3a1",
                                                                                              "521a095c-2c88-4fa0-8a12-2c43a5c49999",
                                                                                              "161907da-f175-4bc8-a173-f3b6e8422d24",
                                                                                              "989fb660-f23b-4326-85a2-074d3e36a732");
            CampaignStatisticsEvents campaignstatisticsevents2 = new CampaignStatisticsEvents("fe3707e3-bf48-48a0-b10e-cadf5408c5cb",
                                                                                              -38,
                                                                                              new Date(1561989476578L),
                                                                                              "655283ee-528f-444e-a96f-00a3b214c702",
                                                                                              "ae05f70c-fcfd-44e3-8a74-57ed7abbf3a1",
                                                                                              "521a095c-2c88-4fa0-8a12-2c43a5c49999",
                                                                                              "161907da-f175-4bc8-a173-f3b6e8422d24",
                                                                                              "989fb660-f23b-4326-85a2-074d3e36a732");
            assertNotNull(campaignstatisticsevents1);
            assertNotNull(campaignstatisticsevents2);
            assertNotSame(campaignstatisticsevents2, campaignstatisticsevents1);
            assertEquals(campaignstatisticsevents2, campaignstatisticsevents1);
            assertEquals(campaignstatisticsevents2.hashCode(), campaignstatisticsevents1.hashCode());
            int hashCode = campaignstatisticsevents1.hashCode();
            for (int i = 0; i < 5; i++) {
                assertEquals(hashCode, campaignstatisticsevents1.hashCode());
            }
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }

    /**
     * Tests the isValid method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testIsValid() {
        CampaignStatisticsEvents campaignstatisticsevents = new CampaignStatisticsEvents("5f105edf-d3bc-4e6f-a5f1-615204a0f248",
                                                                                         -75, new Date(1561989474532L),
                                                                                         "3b859406-80d8-475b-8ab0-e0e36f4539c7",
                                                                                         "3fae6059-d986-4bb0-870d-f3d511a58134",
                                                                                         "32111174-3dc0-4567-bd8d-862eb6045f9d",
                                                                                         "73b274b3-9c5d-41c0-8f10-99edaacba9dc",
                                                                                         "f730b6e2-ee41-4369-8df5-93af14de6ac3");
        assertTrue(campaignstatisticsevents.isValid());
        CampaignStatisticsEvents campaignstatisticseventsInvalid = new CampaignStatisticsEvents(null, 36,
                                                                                                new Date(1561989472430L),
                                                                                                "fe32db3a-9552-4ae9-a719-e2a55606754c",
                                                                                                "ed22f021-8a73-455a-a5d1-d031558b3fa2",
                                                                                                "c8e2843d-75f0-4deb-9291-6e67dc89bef6",
                                                                                                "31fdfa85-add2-480a-86fc-ad1e4898468a",
                                                                                                null);
        assertFalse(campaignstatisticseventsInvalid.isValid());
    }

    /**
     * Tests the equals method.
     */
    @SuppressWarnings("resource")
    @Test
    public void testEquals() {
        try {
            CampaignStatisticsEvents campaignstatisticsevents1 = new CampaignStatisticsEvents("64d1b936-0920-49bb-8daf-05985a62f1ba",
                                                                                              -43,
                                                                                              new Date(1561989477413L),
                                                                                              "0b830f93-94d8-4c6f-9c4c-87262abde3f6",
                                                                                              "37d0dda4-3755-49b6-b8ab-7d004a91c1c5",
                                                                                              "faf9cf6e-c31a-477d-8d16-960b5d148990",
                                                                                              "966a3706-018f-4629-9880-49f73893b9bf",
                                                                                              "10874606-bbe1-48d7-97ba-c2f8f2dad47e");
            CampaignStatisticsEvents campaignstatisticsevents2 = new CampaignStatisticsEvents("64d1b936-0920-49bb-8daf-05985a62f1ba",
                                                                                              -43,
                                                                                              new Date(1561989477413L),
                                                                                              "0b830f93-94d8-4c6f-9c4c-87262abde3f6",
                                                                                              "37d0dda4-3755-49b6-b8ab-7d004a91c1c5",
                                                                                              "faf9cf6e-c31a-477d-8d16-960b5d148990",
                                                                                              "966a3706-018f-4629-9880-49f73893b9bf",
                                                                                              "10874606-bbe1-48d7-97ba-c2f8f2dad47e");
            CampaignStatisticsEvents campaignstatisticsevents3 = new CampaignStatisticsEvents("86f0b827-af4e-4ec7-b20a-3ff1eddb8d14",
                                                                                              109,
                                                                                              new Date(1561989473888L),
                                                                                              "5eb0301d-de7d-418a-8320-0be3dd22248b",
                                                                                              "db5666e4-dd9c-4511-8935-fbaad4a621b3",
                                                                                              "24594c38-342a-4fc7-9b90-4686a5c0e138",
                                                                                              "092cfa73-4ee0-49c6-a1fe-fe19964158da",
                                                                                              "b95389e8-4fd4-47b3-a6ee-7030f9446ac9");
            assertNotNull(campaignstatisticsevents1);
            assertNotNull(campaignstatisticsevents2);
            assertNotNull(campaignstatisticsevents3);
            assertNotSame(campaignstatisticsevents2, campaignstatisticsevents1);
            assertNotSame(campaignstatisticsevents3, campaignstatisticsevents1);
            assertEquals(campaignstatisticsevents2, campaignstatisticsevents1);
            assertEquals(campaignstatisticsevents2, campaignstatisticsevents1);
            assertEquals(campaignstatisticsevents1, campaignstatisticsevents2);
            assertEquals(campaignstatisticsevents1, campaignstatisticsevents1);
            assertFalse(campaignstatisticsevents1.equals(null));
            assertNotEquals(campaignstatisticsevents3, campaignstatisticsevents1);
        } catch (Exception exception) {
            fail(exception.getMessage());
        }
    }
}
